---
- name: Inclui o role do NTP do Linux
  include_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: America/Sao_Paulo
    ntp_manage_config: true
    ntp_servers:
        - "pool.ntp.br iburst"
        - "ntp.cais.rnp.br iburst"
        - "ntp.ufsc.br iburst"