# Primeira coisa adicionaro o usuario ctic ao grupo sudo. Por padrao o acesso por senha no root e desabilitado.
# $ usermod -aG sudo ctic

- hosts: all
  become: true
  become_method: su
  roles:
    - conf_inicial
    - disable_ssh_password
    - sources_list
    - swap_off
    - docker
    - ntp
    - dns_local
    - modulos_kernel_rke

- hosts: all
  become: true
  become_method: su
  tasks:
    - name: Instalar o aptitude, necessario para o modulo apt
      apt: name=aptitude state=latest
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      when: ansible_os_family == 'Debian'
    - name: Remove useless packages from the cache
      apt: autoclean=yes
      when: ansible_os_family == 'Debian'
    - name: Remove dependencies that are no longer required
      apt: autoremove=yes
      when: ansible_os_family == 'Debian'
    - name: Upgrade all packages to the latest version
      apt: name="*" state=latest
      when: ansible_os_family == 'Debian'