image:
  registry: docker.io
  repository: bitnami/owncloud
  tag: 10.2.0-debian-9-r20
  pullPolicy: IfNotPresent
networkPolicyApiVersion: networking.k8s.io/v1

ingress:
  enabled: true
  hosts:
  - name: owncloud.sj.ifsc.edu.br
    tls: true
    certManager: false
    tlsSecret: tls-ingress
    annotations:
  secrets:

owncloudHost: owncloud.sj.ifsc.edu.br
owncloudUsername: user
owncloudPassword: password
owncloudEmail: user@example.com
allowEmptyPassword: "yes"

mariadb:
  enabled: true
  replication:
    enabled: false

  db:
    name: bitnami_owncloud
    user: bn_owncloud
    # password:
  # rootUser:
  #   password:

  master:
    persistence:
      enabled: true
      storageClass: "rook-ceph-block"
      accessMode: ReadWriteOnce
      size: 8Gi

service:
  type: ClusterIP
  port: 80
  nodePorts:
    http: ""
    https: ""
  externalTrafficPolicy: Cluster

persistence:
  enabled: true
  owncloud:
    storageClass: "rook-ceph-block"
    accessMode: ReadWriteOnce
    size: 8Gi

resources:
  requests:
    memory: 512Mi
    cpu: 300m

podAnnotations: {}
metrics:
  enabled: false
