---
- name: Instalar os pacotes necessários para a VPN
  apt: name={{ packages }} state=latest
  vars:
    packages:
    - strongswan-ikev2
    - libstrongswan-extra-plugins

- name: Arquivo ipsec.secrets
  copy:
    src: ipsec.secrets
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: 0644

- name: Habilitar roteamento
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Habilitar roteamento 2
  sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: Habilitar roteamento 3
  sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: 0
    sysctl_set: yes
    state: present
    reload: yes

- name: Habilitar roteamento 4
  sysctl:
    name: net.ipv4.ip_no_pmtu_disc
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Arquivo fln_ipsec.conf
  copy:
    src: fln_ipsec.conf
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_default_ipv4.address == '172.16.0.94'
  notify:
    - restarted strongSwan

- name: Arquivo rei_ipsec.conf
  copy:
    src: rei_ipsec.conf
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_default_ipv4.address == '191.36.0.118'
  notify:
    - restarted strongSwan

- name: Arquivo sje_ipsec.conf
  copy:
    src: sje_ipsec.conf
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_default_ipv4.address == '191.36.8.7'
  notify:
    - restarted strongSwan

- name: Arquivo /etc/strongswan.conf
  copy:
    src: strongswan.conf
    dest: /etc/strongswan.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restarted strongSwan

- name: Enable/Start strongSwan
  service:
    name: strongswan
    state: started
    enabled: no